=== antoniopresas/servicioweb.local/ejercicio2/ejercicio2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="usuarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="usuario">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="apellido" type="xs:string" />
              <xs:element name="direccion">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="pais" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="ciudad" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="Lugo|Pontevedra|Santiago|Coruña"/>
                        </xs:restriction>
                        </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="contacto">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="telefono" type="xs:unsignedInt" />
                    <xs:element name="url" type="xs:string" />
                    <xs:element name="email" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="preferencia" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="email"/>
                          <xs:enumeration value="url"/>
                          <xs:enumeration value="teléfono"/>
                        </xs:restriction>
                      </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:byte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== antoniopresas/servicioweb.local/ejercicio2/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ejercicio2.xsl"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio2.xsd">
    <usuario id="1">
        <nombre>María</nombre>
        <apellido>Boddie</apellido>
        <direccion ciudad="Lugo">Calle Pedro Mar 12
			<pais>España</pais>
		</direccion>
        <contacto preferencia="url">
            <telefono>44221234</telefono>
            <url>http://monnie.ejemplo.com</url>
            <email>monnie@ejemplo.com</email>
        </contacto>
    </usuario>
    <usuario id="2">
        <nombre>Alejandro</nombre>
        <apellido>Gonzalez</apellido>
        <direccion ciudad="Santiago">Calle Luis Angel 22
			<pais>España</pais>
		</direccion>
        <contacto preferencia="email">
            <telefono>44224664</telefono>
            <url>http://ted.ejemplo.com</url>
            <email>ted@ejemplo.com</email>
        </contacto>
    </usuario>
</usuarios>
