=== antoniopresas/servicioweb.local/ejercicio1/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="personas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="persona" maxOccurs="unbounded" minOccurs="2">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="datos">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="nombre"/>
										<xs:element type="xs:string" name="apellidos"/>
									</xs:sequence>
									<xs:attribute type="xs:string" name="provincia" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:short" name="categoria"/>
						</xs:sequence>
						<xs:attribute type="xs:byte" name="id" use="required"/>
						<xs:attribute type="xs:string" name="clave" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== antoniopresas/servicioweb.local/ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="personas.xsl"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio1.xsd">
    <persona id="1" clave="adm">
        <datos provincia="PTV">
            <nombre>María</nombre>
            <apellidos>López</apellidos>
        </datos>
        <categoria>102</categoria>
    </persona>
    <persona id="2" clave="user">
        <datos provincia="PTV">
            <nombre>Rodolfo</nombre>
            <apellidos>Justo</apellidos>
        </datos>
        <categoria>104</categoria>
    </persona>
</personas>
